
[workspace]

[package]
name = "zenoh-runtime-example"
version = "0.1.0"
edition = "2021"

[dependencies]
zenoh-macros = { path = "./zenoh-macros" }
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
tokio = { version = "1", features = ["full"] }

